# Generated by Django 5.2.14 on 2026-05-27 14:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel/Procurement'), ('UTILITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('total_rows', models.IntegerField(default=0)),
                ('parsed_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.datasource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=20)),
                ('raw_data', models.JSONField()),
                ('row_number', models.IntegerField()),
                ('parse_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.ingestionrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.tenant')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=20)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('activity_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('activity_unit', models.CharField(max_length=20)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('ef_source', models.CharField(max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('EDITED_PENDING', 'Edited - Pending Review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected (Legacy)'), ('LOCKED', 'Locked for Audit')], default='PENDING', max_length=20)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_records', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_records', to=settings.AUTH_USER_MODEL)),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ingestion.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.tenant'),
        ),
        migrations.CreateModel(
            name='AuditAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected'), ('EDITED', 'Edited'), ('LOCKED', 'Locked'), ('UNDO', 'Undo'), ('DELETED', 'Deleted')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('normalized_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.normalizedrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['tenant', 'ingestion_run'], name='ingestion_r_tenant__6b89be_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['parse_error'], name='ingestion_r_parse_e_1dbe57_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'status'], name='ingestion_n_tenant__012efe_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'source_type', 'scope'], name='ingestion_n_tenant__f84448_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['is_anomaly'], name='ingestion_n_is_anom_25a371_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'is_deleted'], name='ingestion_n_tenant__adac83_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ingestionrun',
            unique_together={('tenant', 'file_hash')},
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('tenant', 'source_type', 'name')},
        ),
        migrations.AddIndex(
            model_name='auditaction',
            index=models.Index(fields=['tenant', 'performed_at'], name='ingestion_a_tenant__39fb97_idx'),
        ),
        migrations.AddIndex(
            model_name='auditaction',
            index=models.Index(fields=['normalized_record', 'action'], name='ingestion_a_normali_c217ec_idx'),
        ),
    ]
